config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  get 'home/about' => "homes#about", as:"about"
  root to:"homes#top"


  resources :books, only:[:index, :show, :edit, :create, :update, :destroy]
  resources :users, only:[:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,uniqueness: true, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  has_one_attached :profile_image

  has_many :books, dependent: :destroy



  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename:'default-image.jpg',content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book_new = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to "/books"
    end
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      redirect_to book_path(@book_new), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    # if @book.user == current_user
    if  @book.update(book_params)
      redirect_to book_path, notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user == current_user
      @book.destroy
      redirect_to "/books"
    else
      render book_path
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book_new = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user.id), alert:"You only edit your ID"
    end
  end

  def update
    @user = User.find(params[:id])
    # if @user.id == current_user.id
    if  @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<!--エラーメッセージ-->
<div class="text-danger">
  <% if @book_new.errors.any? %>
  <%= pluralize(@book_new.errors.count,"eroor") %> prohibited this obj from being saved:
  <ul>
    <% @book_new.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>


<%= form_with model:@book_new do |f| %>
  <div class="form-group">
    <p>Title</p>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <p>Opinion</p>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class:"btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<h1>Books</h1>
  <table class="table">
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
    <tr>
    <% book.each do |book| %>
      <td><%= link_to image_tag(book.user.get_profile_image(40,40)), user_path(book.user_id) %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>

  </table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>

       <!--エラーメッセージ-->
    <div class="text-danger">
      <% if @book.errors.any? %>
        <%= pluralize(@book.errors.count,"error") %> prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>
    </div>

      <%= form_with model:@book do |f| %>
        <div class="form-group">
          <h4>Title</h4>
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
          <h4>Opinion</h4>
          <%= f.text_area :body, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %>
       | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= render "users/info", user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render "books/form" %>
    </div>

    <div class="col-md-8 offset-md-1">
      <%= render "books/index", book: @books %>
    </div>


  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= render "users/info", user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render "books/form" %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
        <table class="table">
          <tr>
          <!--<= @book.each do |book| %>-->
            <td>
              <%= image_tag @book.user.get_profile_image(50,50) %><br>
              <%= link_to @book.user.name, user_path(@book.user_id) %>
            </td>
            <td><%= link_to @book.title,book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.user.id == current_user.id %>
                <%= link_to "Edit",edit_book_path(@book.id), class:"btn btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user.id == current_user.id %>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>Welcome to <strong><div class="fas fa-book"></div>Bookers!</strong></h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong> !!</h1>
      <p>
        in <strong><i class="fas fa-book"></i>Bookers</strong>,<br>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!
        </p>

        <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in",  new_user_session_path, class:"btn btn-info btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-block mb-3" %>
        </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand p-3" href="/">Bookers</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to  user_path(current_user), class: 'nav-link text-light' do %>
         <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, class: 'nav-link text-light' do %>
          <i class="fas fa-users"></i> Users
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  books_path, class: 'nav-link text-light' do %>
          <i class="fas fa-book-open"></i> Books
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </li>

      <% else %>
      <li class="nav-item">
        <%= link_to "/", class: 'nav-link text-light' do %>
          <i class="fas fa-home"></i> Home
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to about_path, class: 'nav-link text-light' do %>
          <i class="fas fa-link"></i> About
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
          <i class="fas fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
          <i class="fas fa-sign-in-alt"></i> Log in
        <% end %>
      </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="text-success"><%= flash[:notice] %></p>
    <p class="text-danger"><%= flash[:alert] %></p>
    <!--これでもメッセージ表示できる<= notice %>-->
      <%= yield %>
  </body>
</html>

app/views/users/_index.html.erb
<h2>Users</h2>
  <table class="table">
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
    <tr>
    <% user.each do |user| %>
      <td><%= image_tag user.get_profile_image(50,50) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show",user_path(user.id) %></td>
    </tr>
    <% end %>
  </table>

app/views/users/_info.html.erb
  <%= image_tag user.get_profile_image(80,80) %>
  <table class="table">
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>

  <div class="row">
  <!--< if user.id == current_user.id %>-->
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <!--< else %>-->
  <!--  <= link_to user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>-->
  <!--    <i class="fas fa-user-cog"></i>-->
  <!--  < end %>-->
  <!--< end %>-->
  </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
       <!--エラーメッセージ-->
    <div class="text-danger">
      <% if @user.errors.any? %>
        <%= pluralize(@user.errors.count,"error") %> prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>


    </div>
      <h1>User info</h1>
      <%= form_with model:@user do |f| %>
        <div class="form-group">
          <h4>Name</h4>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <h4>Image</h4>
          <%= f.file_field :profile_image, accept:"image/*" %>
        </div>
        <div class="form-group">
          <h4>Introduction</h4>
          <%= f.text_field :introduction, class:"form-control" %><br>
        </div>
        <div class="form-group">
          <%= f.submit "Update User",class:"btn btn-secondary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= render "users/info", user: current_user %>
      <h2 class="mt-3">New book</h2>
        <%= render "books/form" %>
    </div>

    <div class="col-md-8 offset-md-1">
      <%= render "index", user: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
        <%= render "users/info", user: @user %>
      <h2 class="mt-3">New book</h2>
        <%= render "books/form" %>
    </div>

    <div class="col-md-8 offset-md-1">
     
      <%= render "books/index", book: @book %>
    </div>
  </div>
</div>